const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT';

export default {
    ADD_APPOINTMENT,
    DELETE_APPOINTMENT, 
    EDIT_APPOINTMENT
}